##The website title
name: MICSECS-2018
##Markdown processor
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: pygments

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: #/MICSECS-2018 
sass:
  sass_dir: _sass
  style: :compressed
#paginate: 5
#paginate_path: "page:num"

##The website description (to be used in meta tags)
description: The 10th Majorov International Conference on Software Engineering and Computer Systems (MICSECS-2018)
##Some frequently used keywords on your website
keywords: conf, MICSECS, CS, CPS, computer, software, hardware

##define this for disqus comment support
#disqus: forumname

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: analyticsDomain

##Some commonly used links
links:
  facebook: username
  twitter: username
  email: username@gmail.com
  github: username

